[versions]
minecraft = "1.21.5"
fabric-loader = "0.16.14"
fabric-api = "0.124.0+1.21.5"
fabric-loom = "1.11.0-alpha.26"
cloth = "18.0.145"
modmenu = "14.0.0-rc.2"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
cloth-fabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "cloth" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }